version: 2.1

workflows:
  run-collection-workflow:
    jobs:
      - newman-collection-run

jobs:
  newman-collection-run:
    docker:
      - image: node:16-alpine
    steps:
      - checkout
      - run:
          name: Install Newman and postman cloud reporter
          command: npm install -g newman newman-reporter-postman-cloud
      - run:
          name: Run collection and upload results
          command:  newman run "https://api.getpostman.com/collections/20781379-b7630fe7-3388-4759-a4c3-35dff3ab0ced?apikey=${POSTMAN_API_KEY}"  --environment "https://api.getpostman.com/environments/20781379-693005f7-cc91-471f-ab28-5090a42c57c2?apikey=${POSTMAN_API_KEY}" -r postman-cloud --reporter-apiKey "${POSTMAN_API_KEY}" --reporter-workspaceId "e7fc5730-6c18-4af9-af07-806edc6f49c0" --reporter-integrationIdentifier "120219-${CIRCLE_WORKFLOW_JOB_ID}"
            
